In [31]:
import pandas as pd
import functools
file_name = "ventas-enero-febrero"
dir_path = "../data/excel-ventas/"
file_path = f"{dir_path}{file_name}.csv"

@functools.lru_cache(maxsize=1)
def load_data_2(url):
  try:
    df = pd.read_csv(url, encoding='utf-8')
  except UnicodeDecodeError:
    df = pd.read_csv(url, encoding='latin-1')
  return df

In [32]:
consumer_complaint_data = load_data_2(file_path)
consumer_complaint_data.head()

,Fecha Inicial,Fecha Final,Código producto,Nombre producto,Referencia fábrica,Grupo inventario,Cantidad vendida,Valor bruto,Descuento,Subtotal,Impuesto cargo,Impuesto retención,Total
0,01/01/2025,31/01/2025,SVCH,Miguita (Sencillo) Vaso Chocolate,NaN,Productos,63,"384.152,50",0,"384.152,50","88.361,31",0.0,"472.513,81"
1,01/01/2025,31/01/2025,SVMA,Miguita (Sencillo) Vaso Maracuyá,NaN,Productos,91,"554.885,03",0,"554.885,03","127.629,71",0.0,"682.514,74"
2,01/01/2025,31/01/2025,SVVA,Miguita (Sencillo) Vaso Vainilla,NaN,Productos,61,"371.954,66",0,"371.954,66","85.553,24",0.0,"457.507,90"
3,01/01/2025,31/01/2025,SVPC,Miguita (Sencillo) Vaso Panelita de Coco,NaN,Productos,37,"225.609,89",0,"225.609,89","51.890,01",0.0,"277.499,90"
4,01/01/2025,31/01/2025,SVZA,Miguita (Sencillo) Vaso Zapote,NaN,Productos,33,"202.066,51",0,"202.066,51","45.433,36",0.0,"247.499,87"

In [33]:
def transform_sales_data(df):
    def parse_product_name(name):
        mapping = {
            "Miguita (Sencillo) Vaso": ("Vaso", "Miguita"),
            "Miguita (Sencillo) Cono": ("Cono", "Miguita"),
            "Con Ñapa (Doble) Vaso": ("Vaso", "Ñapa"),
            "Con Ñapa (Doble) Cono": ("Cono", "Ñapa"),
            "Pote (Medio Litro)": ("Pote", "Medio Litro"),
            "Tambuco (Litro)": ("Tambuco", "Litro"),
        }

        for key, (presentacion, tamano) in mapping.items():
            if name.startswith(key):
                sabor = name[len(key):].strip()
                return presentacion, sabor, tamano

        return None, name, None

    df[['presentacion', 'sabor', 'tamaño']] = df['Nombre producto'].apply(
        lambda x: pd.Series(parse_product_name(x))
    )

    return df

df = pd.DataFrame(consumer_complaint_data)
df_transformed = transform_sales_data(df)
print(df_transformed)
df_transformed.to_csv(f"transformed_{file_name}.csv", index=False)
print(df_transformed)

    Fecha Inicial Fecha Final Código producto  \
0      01/01/2025  31/01/2025            SVCH
1      01/01/2025  31/01/2025            SVMA
2      01/01/2025  31/01/2025            SVVA
3      01/01/2025  31/01/2025            SVPC
4      01/01/2025  31/01/2025            SVZA
..            ...         ...             ...
246    01/02/2025  28/02/2025            SCVA
247    01/02/2025  28/02/2025            SVAJ
248    01/02/2025  28/02/2025            SVLB
249    01/02/2025  28/02/2025             PPC
250    01/02/2025  28/02/2025            SVKO

                               Nombre producto  Referencia fábrica  \
0            Miguita (Sencillo) Vaso Chocolate                 NaN
1             Miguita (Sencillo) Vaso Maracuyá                 NaN
2             Miguita (Sencillo) Vaso Vainilla                 NaN
3     Miguita (Sencillo) Vaso Panelita de Coco                 NaN
4               Miguita (Sencillo) Vaso Zapote                 NaN
..                                         ...                 ...
246           Miguita (Sencillo) Cono Vainilla                 NaN
247           Miguita (Sencillo) Vaso Ajonjoli                 NaN
248  Miguita (Sencillo) Vaso Limón Hierbabuena                 NaN
249        Pote (Medio Litro) Panelita de Coco                 NaN
250     Miguita (Sencillo) Vaso Kola con Leche                 NaN

    Grupo inventario  Cantidad vendida Valor bruto  Descuento    Subtotal  \
0          Productos                63  384.152,50          0  384.152,50
1          Productos                91  554.885,03          0  554.885,03
2          Productos                61  371.954,66          0  371.954,66
3          Productos                37  225.609,89          0  225.609,89
4          Productos                33  202.066,51          0  202.066,51
..               ...               ...         ...        ...         ...
246        Productos                 1    6.944,44          0    6.944,44
247        Productos                 2   13.888,89          0   13.888,89
248        Productos                 1    6.944,44          0    6.944,44
249        Productos                 1   18.055,56          0   18.055,56
250        Productos                 1    6.944,44          0    6.944,44

    Impuesto cargo  Impuesto retención       Total presentacion  \
0        88.361,31                 0.0  472.513,81         Vaso
1       127.629,71                 0.0  682.514,74         Vaso
2        85.553,24                 0.0  457.507,90         Vaso
3        51.890,01                 0.0  277.499,90         Vaso
4        45.433,36                 0.0  247.499,87         Vaso
..             ...                 ...         ...          ...
246         555,56                 0.0    7.500,00         Cono
247       1.111,11                 0.0   15.000,00         Vaso
248         555,56                 0.0    7.500,00         Vaso
249       1.444,44                 0.0   19.500,00         Pote
250         555,56                 0.0    7.500,00         Vaso

                 sabor       tamaño
0            Chocolate      Miguita
1             Maracuyá      Miguita
2             Vainilla      Miguita
3     Panelita de Coco      Miguita
4               Zapote      Miguita
..                 ...          ...
246           Vainilla      Miguita
247           Ajonjoli      Miguita
248  Limón Hierbabuena      Miguita
249   Panelita de Coco  Medio Litro
250     Kola con Leche      Miguita

[251 rows x 16 columns]
    Fecha Inicial Fecha Final Código producto  \
0      01/01/2025  31/01/2025            SVCH
1      01/01/2025  31/01/2025            SVMA
2      01/01/2025  31/01/2025            SVVA
3      01/01/2025  31/01/2025            SVPC
4      01/01/2025  31/01/2025            SVZA
..            ...         ...             ...
246    01/02/2025  28/02/2025            SCVA
247    01/02/2025  28/02/2025            SVAJ
248    01/02/2025  28/02/2025            SVLB
249    01/02/2025  28/02/2025             PPC
250    01/02/2025  28/02/2025            SVKO

                               Nombre producto  Referencia fábrica  \
0            Miguita (Sencillo) Vaso Chocolate                 NaN
1             Miguita (Sencillo) Vaso Maracuyá                 NaN
2             Miguita (Sencillo) Vaso Vainilla                 NaN
3     Miguita (Sencillo) Vaso Panelita de Coco                 NaN
4               Miguita (Sencillo) Vaso Zapote                 NaN
..                                         ...                 ...
246           Miguita (Sencillo) Cono Vainilla                 NaN
247           Miguita (Sencillo) Vaso Ajonjoli                 NaN
248  Miguita (Sencillo) Vaso Limón Hierbabuena                 NaN
249        Pote (Medio Litro) Panelita de Coco                 NaN
250     Miguita (Sencillo) Vaso Kola con Leche                 NaN

    Grupo inventario  Cantidad vendida Valor bruto  Descuento    Subtotal  \
0          Productos                63  384.152,50          0  384.152,50
1          Productos                91  554.885,03          0  554.885,03
2          Productos                61  371.954,66          0  371.954,66
3          Productos                37  225.609,89          0  225.609,89
4          Productos                33  202.066,51          0  202.066,51
..               ...               ...         ...        ...         ...
246        Productos                 1    6.944,44          0    6.944,44
247        Productos                 2   13.888,89          0   13.888,89
248        Productos                 1    6.944,44          0    6.944,44
249        Productos                 1   18.055,56          0   18.055,56
250        Productos                 1    6.944,44          0    6.944,44

    Impuesto cargo  Impuesto retención       Total presentacion  \
0        88.361,31                 0.0  472.513,81         Vaso
1       127.629,71                 0.0  682.514,74         Vaso
2        85.553,24                 0.0  457.507,90         Vaso
3        51.890,01                 0.0  277.499,90         Vaso
4        45.433,36                 0.0  247.499,87         Vaso
..             ...                 ...         ...          ...
246         555,56                 0.0    7.500,00         Cono
247       1.111,11                 0.0   15.000,00         Vaso
248         555,56                 0.0    7.500,00         Vaso
249       1.444,44                 0.0   19.500,00         Pote
250         555,56                 0.0    7.500,00         Vaso

                 sabor       tamaño
0            Chocolate      Miguita
1             Maracuyá      Miguita
2             Vainilla      Miguita
3     Panelita de Coco      Miguita
4               Zapote      Miguita
..                 ...          ...
246           Vainilla      Miguita
247           Ajonjoli      Miguita
248  Limón Hierbabuena      Miguita
249   Panelita de Coco  Medio Litro
250     Kola con Leche      Miguita

[251 rows x 16 columns]